### ISSUE TITLE
MoveG:FAILED. Reason -> none

### ISSUE THREAD

**Issue by artyomkorchagin** [IFRA-Cranfield/ros2_SimRealRobotControl#18]
Hello, I am trying to move ParallelGripper in gazebo.
This issue happens only when i try to move gripper, robot movements work
I suspect that the robot and the gripper have same topics/nodes like /Move and /RobMove, but i don't know how to fix that yet
Here's what I'm doing:
I've tried to do it with these environments
```
ros2 launch ros2srrc_launch moveit2.launch.py package:=ros2srrc_irb120 config:=irb120_2
ros2 launch ros2srrc_launch moveit2.launch.py package:=ros2srrc_iiwa config:=iiwa_2
``` 
after launching them, i try to move parallelgripper with these:
``` 
ros2 action send_goal /Move ros2srrc_data/action/Move "{action: 'MoveG', moveg: 0.0, speed: 0.5}"
ros2 action send_goal -f /Move ros2srrc_data/action/Move "{action: 'MoveG', moveg: 1.0, speed: 1.0}"
``` 
I get this:
``` 
Waiting for an action server to become available...
Sending goal:
     action: MoveG
speed: 0.5
movej:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  joint7: 0.0
mover:
  joint: ''
  value: 0.0
movel:
  x: 0.0
  y: 0.0
  z: 0.0
moverot:
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
moverp:
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
moveg: 0.0

Goal accepted with ID: 59c1b177796b4ce38948d21baadfbc20

Result:
    result: MoveG:FAILED. Reason -> none

Goal finished with status: SUCCEEDED
``` 
I have the same issue when running sequence (program):
``` 
Specifications:
  Robot: "iiwa"
  EndEffector: "ParallelGripper"
  EELink: "EE_robotiq_2f85"
  Objects: None

Sequence: 
  
  - Step: 1
    Name: "MoveG 0%"
    Type: "MoveG"
    Speed: 1.0
    Delay: 1.0
    Input:
      value: 0.0
  
  - Step: 2
    Name: "MoveG 100%"
    Type: "MoveG"
    Speed: 1.0
    Delay: 1.0
    Input:
      value: 100.0 
    
  - Step: 3
    Name: "MoveG 10%"
    Type: "MoveG"
    Speed: 1.0
    Delay: 1.0
    Input:
      value: 10.0 
``` 
I've also tried doing Type:"ParallelGripper", but i get the same result:
``` 
ros2 run ros2srrc_execution ExecuteProgram.py package:=ros2srrc_execution program:=iiwa_robotiq_2f85
[WARN] [1732447756.807220973] [rcl]: Found remap rule 'package:=ros2srrc_execution'. This syntax is deprecated. Use '--ros-args --remap package:=ros2srrc_execution' instead.
[WARN] [1732447756.807238076] [rcl]: Found remap rule 'program:=iiwa_robotiq_2f85'. This syntax is deprecated. Use '--ros-args --remap program:=iiwa_robotiq_2f85' instead.
==================================================
ROS 2 Sim-to-Real Robot Control: Program Execution
==================================================

PROGRAM -> /ros2srrc_execution/programs/iiwa_robotiq_2f85.yaml found! The sequence is formed by the following steps:

   - Step Number 1:
     MoveG 0%
   - Step Number 2:
     MoveG 100%
   - Step Number 3:
     MoveG 10%

============================================================
Loading Robot+EndEffector Python Clients...

ROBOT: 
[CLIENT - robot.py]: Initialising ROS2 /Move Action Client!
[CLIENT - robot.py]: Waiting for /Move ROS2 ActionServer to be available...
[CLIENT - robot.py]: /Move ACTION SERVER detected, ready!

[CLIENT - robot.py]: Initialising ROS2 /RobMove Action Client!
[CLIENT - robot.py]: Waiting for /Robmove ROS2 ActionServer to be available...
[CLIENT - robot.py]: /Robmove ACTION SERVER detected, ready!

Loaded.

END-EFFECTOR:
[WARN] [1732447756.869766017] [rcl.logging_rosout]: Publisher already registered for provided node name. 
If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. 
As soon as any node with that name is destructed it will unregister the publisher, 
preventing any further logs for that name from being published on the rosout topic.
[CLIENT - robot.py]: Initialising ROS2 /Move Action Client!
[CLIENT - robot.py]: Waiting for /Move ROS2 ActionServer to be available...
[CLIENT - robot.py]: /Move ACTION SERVER detected, ready!

[WARN] [1732447756.877385963] [rcl.logging_rosout]: Publisher already registered for provided node name. 
If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. 
As soon as any node with that name is destructed it will unregister the publisher, 
preventing any further logs for that name from being published on the rosout topic.
[CLIENT - robot.py]: Initialising ROS2 /RobMove Action Client!
[CLIENT - robot.py]: Waiting for /Robmove ROS2 ActionServer to be available...
[CLIENT - robot.py]: /Robmove ACTION SERVER detected, ready!

[CLIENT - parallelGripper.py]: Initialising /ATTACHLINK and /DETACHLINK ROS 2 Service Clients.
[CLIENT - parallelGripper.py]: /ATTACHLINK ROS2 Service ready.
[CLIENT - parallelGripper.py]: /DETACHLINK ROS2 Service ready.

Loaded -> ParallelGripper.

============================================================
============================================================
Executing sequence...

============================================================
Step N1: MoveG 0%

[CLIENT - robot.py]: Move ACTION CALL -> GOAL has been ACCEPTED.
[CLIENT - robot.py]: Move ACTION EXECUTED -> Result: MoveG:FAILED. Reason -> none


ERROR: Execution FAILED!
Message -> MoveG:FAILED. Reason -> none

Closing... BYE!
```
